server: 
  port: 8080
  context-path: /bgms

spring:
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bianpai.cvdkpv1outu9.us-east-2.rds.amazonaws.com:3306/bianpai?characterEncoding=utf8
    username: xuhaobooo
    password: 2732085Ff
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis: 
  mapperLocations: classpath*:sqlMap/**/*.xml
  configLocation: classpath:mybatis-config.xml
  

  